/* Generated By:JavaCC: Do not edit this line. Lexer2Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Lexer2Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int STRLIT = 10;
  /** RegularExpression Id. */
  int INTLIT = 11;
  /** RegularExpression Id. */
  int DBLLIT = 12;
  /** RegularExpression Id. */
  int ID = 56;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int MLC = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"#\"",
    "<token of kind 6>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 9>",
    "<STRLIT>",
    "<INTLIT>",
    "<DBLLIT>",
    "\"class\"",
    "\"extends\"",
    "\"static\"",
    "\"public\"",
    "\"main\"",
    "\"void\"",
    "\"boolean\"",
    "\"int\"",
    "\"double\"",
    "\"String\"",
    "\"true\"",
    "\"false\"",
    "\"new\"",
    "\"this\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"return\"",
    "\"System\"",
    "\"out\"",
    "\"println\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&&\"",
    "\"!\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"=\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "<ID>",
  };

}
