/* Generated By:JavaCC: Do not edit this line. grammar1Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface grammar1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ID = 5;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<ID>",
    "\"-\"",
  };

}
